---
repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.2.0
  #   hooks:
  #     - id: check-merge-conflict
  #     - id: check-symlinks
  #     - id: check-toml
  #     - id: debug-statements
  #     - id: detect-aws-credentials
  #       args: [--allow-missing-credentials]
  #     - id: detect-private-key
  #     - id: end-of-file-fixer
  #     - id: trailing-whitespace

  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.26.3
  #   hooks:
  #     - id: yamllint

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort

  # - repo: https://github.com/myint/autoflake
  #   rev: v1.4
  #   hooks:
  #     - id: autoflake
  #       args:
  #         [
  #           --in-place,
  #           --ignore-init-module-imports,
  #           --remove-unused-variables,
  #           --remove-all-unused-imports,
  #         ]

  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black

  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.1
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/PyCQA/doc8
  #   rev: v1.0.0
  #   hooks:
  #     - id: doc8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --configfile
          - .bandit.yaml

  # - repo: https://github.com/stelligent/cfn_nag
  #   rev: v0.8.10
  #   hooks:
  #     - id: cfn-nag
  #       files: .*\.(yaml|yml)$
  #       exclude: >
  #         (?x)^(
  #           .pre-commit-config.yaml|
  #           .gitlab-ci.yml|
  #           .bandit.yaml|
  #           .yamllint.yaml|
  #           .checkov.yaml|
  #           .tox|
  #           .venv|
  #           .nenv|
  #           cdk.out|
  #           ddk.out
  #         )

  # - repo: https://github.com/bridgecrewio/checkov.git
  #   rev: 2.0.1041
  #   hooks:
  #     - id: checkov
  #       verbose: true
  #       args:
  #         - --compact
  #         - --config-file
  #         - .checkov.yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
    - id: python-safety-dependencies-check
      files: requirements

  # run `export GOPROXY=direct` prior to `pre-commit install`
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.9.0
    hooks:
      - id: gitleaks
        entry: gitleaks detect -v --redact --no-git -s .
